### ISSUE TITLE
Техническое задание: Список заинтересованных лиц и требования каждого из них

### ISSUE THREAD

**Issue by vityaman** [vityaman-edu/nexo-hub#18]
## Описание

В презентации нашел такие слова про ТЗ:

>  Составляете список заинтересованных лиц (например, мы делаем какую-то систему для какого-то завода)
> • Директор завода
> • Мастер цеха
> • Бухгалтер
> • Главный инженер
> • Рабочий
> • Охранник
> • Дворник
> • Гость/посетитель
> • Разработчик системы
> ...
> Составляете список требований для каждого из заинтересованных лиц

Предлагаю добавить раздел с заинтересованными лицами и списком требований для каждого их них. Возможно, мы можем просто перечислить идентификаторы требований для каждого лица.

## Критерий завершения

- Влит MR с правками в ТЗ, добавлен раздел "Заинтересованные лица" и перечислены требования каждого.

## Ресурсы

- Презентация по лекции 1: 35 слайд

**Comment by vityaman** [comment]
@Andryss, что думаешь насчет этого? Надо делать?

**Comment by Andryss** [comment]
@vityaman, думаю надо будет, но в другом виде

**Comment by vityaman** [comment]
@Andryss, почему ты переоткрыл тикет?

**Comment by Andryss** [comment]
@vityaman вообще закрыл случайно, но теперь понял, что его и закрыть можно

**Comment by vityaman** [comment]
> @vityaman, думаю надо будет, но в другом виде

@Andryss, а в каком виде нужно?

**Comment by Andryss** [comment]
@vityaman в том ГОСТе, что показали нам в пятницу есть наименование компании-заказчика и наименование клипании-разработчика

**Comment by Andryss** [comment]
Сам ГОСТ в тикете #25
