### ISSUE TITLE
Разработать документ, описывающий архитектуру системы

### ISSUE THREAD

**Issue by Andryss** [vityaman-edu/nexo-hub#2]
## Описание

Комментарии Аркадия Олеговича предлагаю писать в комментарии к этому тикету.

## Критерий завершения

- Замерджен MR с финальной версией markdown документа -- дизайном архитектуры системы.
- Архитекура утверждена Аркадием Олеговичем.

## Ресурсы

- #1

**Comment by vityaman** [comment]
- [SVT Analytics Software Architecture Document](https://upcommons.upc.edu/bitstream/handle/2099.1/18373/90629.pdf)
