### ISSUE TITLE
Разобраться с очередью сообщений

### ISSUE THREAD

**Issue by YuikoSempai** [vityaman-edu/nexo-hub#24]
Что нужно сделать в рамках задачи:
- Понять какую очередь мы можем/нам нужно использовать - Redis (done)
- Понять можно ли будет из нашей очереди читать по событию а не по тайминг, и если только по таймингу, то понять какой будет удачный и что не вызовет сильную нагрузку на приложение
- Попытаться настроить хоть какой-то сервис который будет писать в очередь и читать из нее, чтобы это можно было в дальнейшем использовать в других сервисах

**Comment by YuikoSempai** [comment]
Выжимка из "Спринт 1"
- Общаться только через брокер сообщений
- Очередь размазана
- Очереди нужно убрать если мы говорим о сервисах
- Очередь -- интерфейс

**Comment by vityaman** [comment]
@YuikoSempai, кажется, что в качестве брокера сообщений нужно использовать Redis, такие требования выставил Ключев.

**Comment by YuikoSempai** [comment]
Окей, с тем что использовать определились, осталось два пункта еще

**Comment by Andryss** [comment]
@YuikoSempai https://github.com/Andryss/ktor-redis-sample

**Comment by Andryss** [comment]
Сервис с записью в логи и использованием очереди можно найти в ветке `test-log-service`
