### ISSUE TITLE
Разработать Use-Case диаграмму, продумать пользовательские сценарии

### ISSUE THREAD

**Issue by e1turin** [vityaman-edu/nexo-hub#31]
Необходимо продумать пользовательские сценарии и построить Use-Case диаграмму для определения требуемых к реализации функций в приложении.

Для генерации идей вариантов использования приложения (пользовательских сценариев) соданно обсуждение https://github.com/vityaman-edu/nexo-hub/discussions/26, на основе которого строится Use-Case диаграмма.

Текущий вариант диаграммы:

![Image](https://github.com/vityaman-edu/nexo-hub/assets/48864186/d6e04cad-b67a-4fb4-b08a-e49ab246125c)

**Comment by Andryss** [comment]
@e1turin , мне кажется, что тип устройства должен определяться нашим сервисом. Может лучше заменить "выбрать тип устройства" на "выбрать комнату"? Или работа с комнатами == работа с группами?

**Comment by e1turin** [comment]
> Или работа с комнатами == работа с группами?

Да, я рассматриваю более общий вариант, когда пользователю нужно просто каким-то образом сделать группу устройств, например, для одной комнаты. Я ни как не говорю про то как именно группировку сделать (теги/помещения/др.)

> тип устройства должен определяться нашим сервисом.

Всё так. У пользователя просто есть потребность выбрать подходящий ему тип (вид/класс) устройств, чтобы добавить его в свое приложение. Сами же типы мы предоставляем через наши сервисы. Возможно стоит использовать другое слово для обозначения "типа*.

**Comment by Andryss** [comment]
> У пользователя просто есть потребность выбрать подходящий ему тип (вид/класс) устройств, чтобы добавить его в свое приложение.

То есть условно при добавлении (поиске) нового устройства это будет как фильтр по найденным устройствам?

**Comment by e1turin** [comment]
Вроде того. Сам способ выбора зависит от реализации. Важно что есть разные виды устройств и при добавлении устройства в приложении нужно определить его вид. Возможно придётся упростить систему до одного типа с любым количеством контроллеров. Но пока мне кажется, что между лампочкой и чайником есть различие, и управление ими происходит по-разному.
