### ISSUE TITLE
Вынести общую функциональность в библиотеку

### ISSUE THREAD

**Issue by Andryss** [vityaman-edu/nexo-hub#35]
Сейчас во всех сервисах есть общие классы (типа [Model.kt](https://github.com/vityaman-edu/nexo-hub/blob/prototype/connection-service/src/main/kotlin/org/vivlaniv/nexohub/Model.kt) или [Logger.kt](https://github.com/vityaman-edu/nexo-hub/blob/prototype/connection-service/src/main/kotlin/org/vivlaniv/nexohub/Logger.kt)).

Нужно вынести эти файлы в отдельную библиотеку. И через build.gradle.kts подключить эту библиотеку в другие сервисы.

Связанный: #32

**Comment by e1turin** [comment]
наверное библиотека это пока лишнее. Достаточно common-модуля

**Comment by Andryss** [comment]
@e1turin да, модуль наверное и имел в виду. Проcто не очень понимаю разницу между

**Comment by e1turin** [comment]
Ты же можешь сделать библиотеку, которую запушишь в maven-central. как делают с SDK (на примере Meetacy :))
