### ISSUE TITLE
Наладить процесс разработки

### ISSUE THREAD

**Issue by vityaman** [vityaman-edu/nexo-hub#4]
## Описание

Хочется иметь зафиксированное описание процесса разработки в нашей команде.

Следует включить туда:

- Какие встречи мы проводим, когда и с какой целью
- Как создавать задачи, как называть коммиты, MRы

## Критерий завершения

- Описаны встречи, все члены команды согласны с регламентом.

## Ресурсы

- [Scrum Guide](https://scrumguides.org/scrum-guide.html)

**Comment by vityaman** [comment]
## Встречи

Мы стараемся подражать метологии Scrum, поэтому организуем соответствующие встречи. Созваниваться предлагается в Telegram.

### Ревью

Это встреча с заказчиком, презентация решений, получение фидбека, генерация новых задач в бэклог. Более подробно проходит в несколько шагов:

1. Вспоминаем состояние проекта на момент прошлой встречи.
2. Показываем, какие задачи были взяты на текущий спринт, во сколько были оценены, каков прогресс по каждой из них.
3. Демонстрируем работоспособность новой функциональности системы.
4. Задаем волнующие нас вопросы, получаем ответы.
5. Принимаем новые требования, правки.
6. Фиксируем все письменно, чтобы не забыть.

Встреча проходит каждую вторую пятницу во время пары по мобилкам.

### Ретроспектива

Смотрим, что мы сделали за спринт, что было хорошо, что было плохо, что хотелось бы улучшить, что хотелось бы убрать. Предлагается следовать шаблонам, для которых сделаны [доски в Miro](https://miro.com/agile/guide-to-retrospectives/). Предложения приветствуются.

Встреча проходит сразу после **Ревью** и длится 45 минут.

### Планирование

Определяем цели спринта, выбираем задачи, оцениваем их (в sp), распределяем по людям. Все новые тикеты должны быть созданы и описаны к моменту начала встречи. Мы смотрим на каждую задачу по очереди, обсуждаем, что должно быть сделано и как, а также выбираем исполнителя.

Встреча проходит каждую вторую субботу в ~18:00.

**Comment by vityaman** [comment]
## Как создавать задачи, как называть коммиты, MRы

- Имя MR: `#номер_тикета Описание описание, описание`.
- Сквашить MR.
- Для задачи хочется иметь описание конкретных критериев ее завершения.
- Хочется ставить дедлайны для задач, чтобы тренироваться оценивать таски.
- Если создаем МР для прогонки CI, то отмечаем его как черновик, чтобы никто с дури не начал ревьювить.

**Comment by vityaman** [comment]
Надо подумать, будем ли мы кидать МРы на доску задач.

**Comment by Andryss** [comment]
Наладил 👍
