### ISSUE TITLE
Заполнить раздел с техническими требованиями из технического задания

### ISSUE THREAD

**Issue by Andryss** [vityaman-edu/nexo-hub#9]
## Описание

Расписать раздел "3 Технические требования". 

## Критерий завершения

Влит MR с заполненным разделом в ТЗ

## Ресурсы

- #1

**Comment by vityaman** [comment]
@Andryss, do I understand correctly, that I need to come up with them using SRS document template? Or we have also some source of ideas and areas to think about?

**Comment by Andryss** [comment]
@vityaman, you should generate requirements according to presentation, group them and put into SRS document
